# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisement/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisement/
Content-Type: application/json
Authorization: Token 7f7577f4bc71d548a001e67d583a655faf80bd1b

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisement/1/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisement/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisement/?created_at_before=2020-10-01
Content-Type: application/json
